### PR TITLE
Added short profile with readme.md file.

### PR DESCRIPTION
**Pull request by VedantSharma11**
@mitalrs pls review and merge this with #hacktoberfest-accepted tag

### CODE REVIEW

**Comment by VedantSharma11** [comment]
but i have followed all the rules mentioned in the readme.
1) i forked the repo and then created a new branch then i added my code with my name as folder name in the new branch i made.
2) then i added readme in my folder.
3) and then i added my name to the contributing.md as mentioned in your repo's readme.
4) and then i raised PR from the branch i created.

i dont know what is the issue here . Please explain what do i need to correct

**Comment by VedantSharma11** [comment]
pls reply @mitalrs

**Comment by VedantSharma11** [comment]
.

**Comment by VedantSharma11** [comment]
Buddy I'm not able to get what the issue is
I'm making a seperate folder and making changes in it and im not making
changes in the existing folders
Can you please specify what it is that I'm doing wrong?

**Comment by mitalrs** [comment]
@VedantSharma11 
sorry for late response but now I'm not able to see you so i cant figure it out.

**Pull request closed without merging**
