### PR TITLE
Add profile card for Sandesh GC

### LINKED ISSUE #34: Add profile card for Sandesh GC
I would like to add my profile card to the repository.
Assign me.

### PR DESCRIPTION
**Pull request by gcsandesh**
I have added a short profile card for myself in a new folder.
This resolves #34

### CODE REVIEW

**Comment by mitalrs** [comment]
@SandeshGC 
check your pr i can't see your pr

**Comment by SandeshGC** [comment]
This is my PR #36

**Comment by mitalrs** [comment]
@SandeshGC 
sorry, my bad not pr i want to say folder

**Comment by SandeshGC** [comment]
It is in the first commit.

**Comment by mitalrs** [comment]
@SandeshGC 
can you done sync fork on your for repo??

**Comment by SandeshGC** [comment]
Done!

**Pull request closed without merging**
